#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.buffering import Buffer
from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS, generic_main  # noqa


KEYWORDS = {}


class LinneaBuffer(Buffer):
    def __init__(
        self,
        text,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re='#.*?$',
        ignorecase=None,
        namechars='',
        **kwargs
    ):
        super().__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class LinneaParser(Parser):
    def __init__(
        self,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re='#.*?$',
        ignorecase=None,
        left_recursion=False,
        parseinfo=True,
        keywords=None,
        namechars='',
        buffer_class=LinneaBuffer,
        **kwargs
    ):
        if keywords is None:
            keywords = KEYWORDS
        super().__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            buffer_class=buffer_class,
            **kwargs
        )

    @graken()
    def _identifier_(self):
        self._pattern(r'[a-zA-Z_][a-zA-Z0-9_]*')

    @graken()
    def _constant_(self):
        self._pattern(r'[0-9]+(\.[0-9]+)?([Ee][+-]?[0-9]+)?')

    @graken()
    def _integer_(self):
        self._pattern(r'[0-9]+')

    @graken('Model')
    def _model_(self):
        self._var_declarations_()
        self.name_last_node('vars')
        self._symbol_declarations_()
        self.name_last_node('symbols')
        self._equations_()
        self.name_last_node('equations')
        self._check_eof()
        self.ast._define(
            ['equations', 'symbols', 'vars'],
            []
        )

    @graken()
    def _var_declarations_(self):

        def block0():
            self._var_declaration_()
            self.add_last_node_to_name('@')
        self._closure(block0)

    @graken()
    def _symbol_declarations_(self):

        def block0():
            self._symbol_declaration_()
            self.add_last_node_to_name('@')
        self._closure(block0)

    @graken()
    def _equations_(self):

        def block0():
            self._equation_()
            self.add_last_node_to_name('@')
        self._closure(block0)

    @graken('Size')
    def _var_declaration_(self):
        self._identifier_()
        self.name_last_node('name')
        self._token('=')
        self._cut()
        self._integer_()
        self.name_last_node('value')
        self.ast._define(
            ['name', 'value'],
            []
        )

    @graken()
    def _symbol_declaration_(self):
        with self._choice():
            with self._option():
                self._scalar_()
            with self._option():
                self._row_vector_()
            with self._option():
                self._column_vector_()
            with self._option():
                self._matrix_()
            with self._option():
                self._identity_matrix_()
            self._error('no available options')

    @graken('Scalar')
    def _scalar_(self):
        self._token('Scalar')
        self._cut()
        self._identifier_()
        self.name_last_node('name')
        self._token('<')
        self._io_()
        self.name_last_node('iotype')
        self._token('>')
        self.ast._define(
            ['iotype', 'name'],
            []
        )

    @graken('RowVector')
    def _row_vector_(self):
        self._token('RowVector')
        self._cut()
        self._identifier_()
        self.name_last_node('name')
        self._dim_vector_()
        self.name_last_node('dims')
        self._token('<')
        self._io_()
        self.name_last_node('iotype')

        def block3():
            self._token(',')
            self._properties_()
            self.add_last_node_to_name('properties')
        self._closure(block3)
        self._token('>')
        self.ast._define(
            ['dims', 'iotype', 'name'],
            ['properties']
        )

    @graken('ColumnVector')
    def _column_vector_(self):
        self._token('ColumnVector')
        self._cut()
        self._identifier_()
        self.name_last_node('name')
        self._dim_vector_()
        self.name_last_node('dims')
        self._token('<')
        self._io_()
        self.name_last_node('iotype')

        def block3():
            self._token(',')
            self._properties_()
            self.add_last_node_to_name('properties')
        self._closure(block3)
        self._token('>')
        self.ast._define(
            ['dims', 'iotype', 'name'],
            ['properties']
        )

    @graken('Matrix')
    def _matrix_(self):
        self._token('Matrix')
        self._cut()
        self._identifier_()
        self.name_last_node('name')
        self._dim_matrix_()
        self.name_last_node('dims')
        self._token('<')
        self._io_()
        self.name_last_node('iotype')

        def block3():
            self._token(',')
            self._properties_()
            self.add_last_node_to_name('properties')
        self._closure(block3)
        self._token('>')
        self.ast._define(
            ['dims', 'iotype', 'name'],
            ['properties']
        )

    @graken('IdentityMatrix')
    def _identity_matrix_(self):
        self._token('IdentityMatrix')
        self._cut()
        self._identifier_()
        self.name_last_node('name')
        self._dim_matrix_()
        self.name_last_node('dims')
        self.ast._define(
            ['dims', 'name'],
            []
        )

    @graken()
    def _io_(self):
        with self._choice():
            with self._option():
                self._token('Input')
            with self._option():
                self._token('Output')
            with self._option():
                self._token('InOut')
            with self._option():
                self._token('Intermediate')
            self._error('expecting one of: InOut Input Intermediate Output')

    @graken()
    def _dim_vector_(self):
        self._token('(')
        self._identifier_()
        self.name_last_node('length')
        self._token(')')
        self.ast._define(
            ['length'],
            []
        )

    @graken()
    def _dim_matrix_(self):
        self._token('(')
        self._identifier_()
        self.name_last_node('rows')
        self._token(',')
        self._identifier_()
        self.name_last_node('columns')
        self._token(')')
        self.ast._define(
            ['columns', 'rows'],
            []
        )

    @graken()
    def _properties_(self):
        with self._choice():
            with self._option():
                self._token('Square')
                self.name_last_node('@')
            with self._option():
                self._token('SPD')
                self.name_last_node('@')
            with self._option():
                self._token('ColumnPanel')
                self.name_last_node('@')
            with self._option():
                self._token('RowPanel')
                self.name_last_node('@')
            with self._option():
                self._token('Diagonal')
                self.name_last_node('@')
            with self._option():
                self._token('Tridiagonal')
                self.name_last_node('@')
            with self._option():
                self._token('Banded')
                self.name_last_node('@')
            with self._option():
                self._token('LowerTriangular')
                self.name_last_node('@')
            with self._option():
                self._token('UpperTriangular')
                self.name_last_node('@')
            with self._option():
                self._token('UnitDiagonal')
                self.name_last_node('@')
            with self._option():
                self._token('Symmetric')
                self.name_last_node('@')
            with self._option():
                self._token('Hessenberg')
                self.name_last_node('@')
            with self._option():
                self._token('Orthogonal')
                self.name_last_node('@')
            with self._option():
                self._token('FullRank')
                self.name_last_node('@')
            with self._option():
                self._token('Non-singular')
                self.name_last_node('@')
            self._error('expecting one of: Banded ColumnPanel Diagonal FullRank Hessenberg LowerTriangular Non-singular Orthogonal RowPanel SPD Square Symmetric Tridiagonal UnitDiagonal UpperTriangular')

    @graken('Equation')
    def _equation_(self):
        self._symbol_()
        self.name_last_node('lhs')
        self._token('=')
        self._cut()
        self._expression_()
        self.name_last_node('rhs')
        self.ast._define(
            ['lhs', 'rhs'],
            []
        )

    @graken()
    def _expression_(self):
        with self._choice():
            with self._option():
                self._addition_()
            with self._option():
                self._subtraction_()
            with self._option():
                self._term_()
            self._error('no available options')

    @graken('Plus')
    def _addition_(self):
        self._term_()
        self.name_last_node('left')
        self._token('+')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @graken('Subtract')
    def _subtraction_(self):
        self._term_()
        self.name_last_node('left')
        self._token('-')
        self.name_last_node('op')
        self._cut()
        self._expression_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @graken()
    def _term_(self):
        with self._choice():
            with self._option():
                self._multiplication_()
            with self._option():
                self._factor_()
            self._error('no available options')

    @graken('Times')
    def _multiplication_(self):
        self._factor_()
        self.name_last_node('left')
        self._token('*')
        self.name_last_node('op')
        self._cut()
        self._term_()
        self.name_last_node('right')
        self.ast._define(
            ['left', 'op', 'right'],
            []
        )

    @graken()
    def _factor_(self):
        with self._choice():
            with self._option():
                self._subexpression_()
            with self._option():
                self._transposed_expr_()
            with self._option():
                self._inverted_expr_()
            with self._option():
                self._literal_expr_()
            with self._option():
                self._symbol_()
            self._error('no available options')

    @graken()
    def _subexpression_(self):
        self._token('(')
        self._cut()
        self._expression_()
        self.name_last_node('@')
        self._token(')')

    @graken('Transpose')
    def _transposed_expr_(self):
        with self._choice():
            with self._option():
                self._token('trans(')
                self._expression_()
                self.name_last_node('arg')
                self._token(')')
            with self._option():
                self._factor_()
                self.name_last_node('arg')
                self._token("'")
            self._error('no available options')
        self.ast._define(
            ['arg'],
            []
        )

    @graken('Inverse')
    def _inverted_expr_(self):
        self._token('inv(')
        self._expression_()
        self.name_last_node('arg')
        self._token(')')
        self.ast._define(
            ['arg'],
            []
        )

    @graken('Number')
    def _literal_expr_(self):
        self._constant_()
        self.name_last_node('value')
        self.ast._define(
            ['value'],
            []
        )

    @graken('Symbol')
    def _symbol_(self):
        self._identifier_()
        self.name_last_node('name')
        self.ast._define(
            ['name'],
            []
        )


class LinneaSemantics():
    def identifier(self, ast):
        return ast

    def constant(self, ast):
        return ast

    def integer(self, ast):
        return ast

    def model(self, ast):
        return ast

    def var_declarations(self, ast):
        return ast

    def symbol_declarations(self, ast):
        return ast

    def equations(self, ast):
        return ast

    def var_declaration(self, ast):
        return ast

    def symbol_declaration(self, ast):
        return ast

    def scalar(self, ast):
        return ast

    def row_vector(self, ast):
        return ast

    def column_vector(self, ast):
        return ast

    def matrix(self, ast):
        return ast

    def identity_matrix(self, ast):
        return ast

    def io(self, ast):
        return ast

    def dim_vector(self, ast):
        return ast

    def dim_matrix(self, ast):
        return ast

    def properties(self, ast):
        return ast

    def equation(self, ast):
        return ast

    def expression(self, ast):
        return ast

    def addition(self, ast):
        return ast

    def subtraction(self, ast):
        return ast

    def term(self, ast):
        return ast

    def multiplication(self, ast):
        return ast

    def factor(self, ast):
        return ast

    def subexpression(self, ast):
        return ast

    def transposed_expr(self, ast):
        return ast

    def inverted_expr(self, ast):
        return ast

    def literal_expr(self, ast):
        return ast

    def symbol(self, ast):
        return ast


def main(filename, startrule, **kwargs):
    with open(filename) as f:
        text = f.read()
    parser = LinneaParser()
    return parser.parse(text, startrule, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from grako.util import asjson

    ast = generic_main(main, LinneaParser, name='Linnea')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(asjson(ast), indent=2))
    print()
